### ISSUE TITLE
Issue with reindex

### ISSUE THREAD

**Issue by IslamHali** [tzyganu/rule-products#5]
Hello,

When i try to install this extension i get a message to reindex
Clear Product rule pages & Rebuild Product rule pages

But when i do i get this error: 

Invalid entity_type specified: easylife_ruleproducts_ruleproduct

And the rule is shown but giving this error page:

Magento Commerce
There has been an error processing your request
Invalid entity_type specified: easylife_ruleproducts_ruleproduct

Trace:
#0 /home/tgbullionworld/public_html/app/code/core/Mage/Eav/Model/Config.php(328): Mage::throwException('Invalid entity_...')
#1 /home/tgbullionworld/public_html/app/code/core/Mage/Eav/Model/Entity/Abstract.php(276): Mage_Eav_Model_Config->getEntityType('easylife_rulepr...')
#2 /home/tgbullionworld/public_html/app/code/community/Easylife/RuleProducts/Model/Resource/Ruleproduct.php(38): Mage_Eav_Model_Entity_Abstract->setType('easylife_rulepr...')
#3 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Model/Config.php(1357): Easylife_RuleProducts_Model_Resource_Ruleproduct->__construct(Array)
#4 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Model/Config.php(1389): Mage_Core_Model_Config->getModelInstance('easylife_rulepr...', Array)
#5 /home/tgbullionworld/public_html/app/Mage.php(491): Mage_Core_Model_Config->getResourceModelInstance('easylife_rulepr...', Array)
#6 /home/tgbullionworld/public_html/app/Mage.php(519): Mage::getResourceModel('easylife_rulepr...', Array)
#7 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Model/Abstract.php(139): Mage::getResourceSingleton('easylife_rulepr...')
#8 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Model/Abstract.php(208): Mage_Core_Model_Abstract->_getResource()
#9 /home/tgbullionworld/public_html/app/code/core/Mage/Catalog/Model/Abstract.php(211): Mage_Core_Model_Abstract->getResourceCollection()
#10 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Model/Abstract.php(213): Mage_Catalog_Model_Abstract->getResourceCollection()
#11 /home/tgbullionworld/public_html/app/code/community/Easylife/RuleProducts/Block/Adminhtml/Ruleproduct/Grid.php(50): Mage_Core_Model_Abstract->getCollection()
#12 /home/tgbullionworld/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(643): Easylife_RuleProducts_Block_Adminhtml_Ruleproduct_Grid->_prepareCollection()
#13 /home/tgbullionworld/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(649): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#14 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(922): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#15 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#16 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#17 /home/tgbullionworld/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#18 /home/tgbullionworld/public_html/app/design/adminhtml/default/default/template/easylife_ruleproducts/grid.phtml(32): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#19 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/tgbullion...')
#20 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#21 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#22 /home/tgbullionworld/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#23 /home/tgbullionworld/public_html/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#24 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#25 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#26 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#27 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#28 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#29 /home/tgbullionworld/public_html/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#30 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/tgbullion...')
#31 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#32 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#33 /home/tgbullionworld/public_html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#34 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#35 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#36 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#37 /home/tgbullionworld/public_html/app/code/community/Easylife/RuleProducts/controllers/Adminhtml/Ruleproducts/RuleproductController.php(74): Mage_Core_Controller_Varien_Action->renderLayout()
#38 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Easylife_RuleProducts_Adminhtml_Ruleproducts_RuleproductController->indexAction()
#39 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#40 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#41 /home/tgbullionworld/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#42 /home/tgbullionworld/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#43 /home/tgbullionworld/public_html/index.php(83): Mage::run('', 'store')
#44 {main}

Error log record number: [1390382967620](https://torontogoldbullion.com/errors/report.php?id=1390382967620&skin=default)

Magento is a trademark of Magento Inc. Copyright © 2017 Magento Inc.

**Comment by IslamHali** [comment]
Can you please help with that,
I appreciate your help,
Thanks,

Saimon

**Comment by tzyganu** [comment]
@IslamHali Sorry, but I don't have the time anymore to work on this extensnion. Magento 1 has reached and of life.
